# Generated by Django 4.1.7 on 2023-08-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HousingListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("post_text", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "number_of_rooms",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("image_url", models.TextField()),
                ("post_id", models.TextField()),
                ("user_id", models.TextField()),
                ("address", models.TextField()),
                ("time", models.TextField()),
            ],
        ),
    ]
