# Generated by Django 4.1.7 on 2023-08-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_housinglisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housinglisting",
            name="number_of_rooms",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="housinglisting", name="price", field=models.FloatField(),
        ),
    ]
