# Generated by Django 4.1.7 on 2023-08-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_housinglisting_number_of_rooms_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="housinglisting", name="id",),
        migrations.RemoveField(model_name="housinglisting", name="title",),
        migrations.AlterField(
            model_name="housinglisting",
            name="post_text",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
